version: "3.9"

services:
  db:
    image: postgres:16
    container_name: subscriptions-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: subscriptions-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ADDR: ":8080"
      APP_LOG_LEVEL: "debug"
      APP_SHUTDOWN_TIMEOUT: "5s"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "subscriptions"
      DB_SSLMODE: "disable"
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata: